
run-name: commit ${{github.sha}} deployment
on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js 18
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Install Frontend
      run: npm run install-frontend

    - name: Build Frontend
      run: npm run build

    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
        aws-secret-access-key: ${{secrets.AWS_ACCESS_KEY_SECRET}}
        aws-region: eu-west-1

    - name: Deploy with CDK
      run: npm run cdk -- deploy --required-approval never